spring:
  mail:
    host: localhost
    port: 1025
    username: mail
    password: mail
    properties:
      mail:
        smtp:
          trust: all
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 5000
        waittilltimeout: 5000
  application:
    security:
      jwt:
        secret: 69df7a15a26dfe41b8653422222c35f32f3c3b0b92cf1f01cbf589b7f224b58b
        expiration: 86400
    mailing:
      frontend:
        activation-url: http://localhost:8080/api/v1/auth/activate